service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000

[[fileservice]]
backend = "MINIO"
name = "SHARED"

[fileservice.s3]
bucket = "bucket"
endpoint = "http://localhost:9000"

