service-type = "TN"
data-dir = "./mo-data"

[log]
level = "info"

[tn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 19000

[[fileservice]]
backend = "MINIO"
name = "SHARED"

[fileservice.s3]
bucket = "bucket"
endpoint = "http://localhost:9000"

